version: '3.1'

services:

    php-apache:
        build: ./php-apache
        ports:
            - 80
        #volumes:
        #    - ./php-apache/DocumentRoot:/var/www/html

        env_file: 
            - ../private-environment.txt
            - ./private-environment.txt
        environment:
            - MYSQL_HOST=mariadb
            - MYSQL_DATABASE=qa
            - MYSQL_USER=qa
            - VIRTUAL_HOST=questions.sandiegodata.org
            - LETSENCRYPT_HOST=questions.sandiegodata.org


volumes:
    html: {}
        
networks:
  default:
    external:
      name: webproxy


